require 'integer_extensions'

require 'character'
require 'attack'

require 'standard_class'
require 'fighter_class'
require 'rogue_class'
require 'war_monk_class'
require 'paladin_class'

require 'standard_race'
require 'human_race'
require 'orc_race'
require 'dwarf_race'
require 'elf_race'
require 'halfling_race'

require 'basic_weapon'
require 'bare_hands'
require 'longsword'
require 'elven_longsword'
require 'war_axe'
require 'magic_war_axe'
require 'nun_chucks'
